var population = [
 {"state":"Alaska", "population":47},
 {"state":"Texas", "population":2},
 {"state":"California", "population":1},
 {"state":"Montana", "population":44},
 {"state":"New Mexico", "population":36},
 {"state":"Arizona", "population":15},
 {"state":"Nevada", "population":35},
 {"state":"Colorado", "population":22},
 {"state":"Wyoming", "population":51},
 {"state":"Oregon", "population":27},
 {"state":"Idaho", "population":39},
 {"state":"Utah", "population":33},
 {"state":"Kansas", "population":34},
 {"state":"Minnesota", "population":21},
 {"state":"Nebraska", "population":37},
 {"state":"South Dakota", "population":46},
 {"state":"North Dakota", "population":48},
 {"state":"Missouri", "population":18},
 {"state":"Oklahoma", "population":28},
 {"state":"Washington", "population":13},
 {"state":"Georgia", "population":8},
 {"state":"Michigan", "population":9},
 {"state":"Iowa", "population":30},
 {"state":"Illinois", "population":5},
 {"state":"Wisconsin", "population":20},
 {"state":"Florida", "population":4},
 {"state":"Arkansas", "population":32},
 {"state":"Alabama", "population":23},
 {"state":"North Carolina", "population":10},
 {"state":"New York", "population":3},
 {"state":"Mississippi", "population":31},
 {"state":"Pennsylvania", "population":6},
 {"state":"Louisiana", "population":25},
 {"state":"Tennessee", "population":17},
 {"state":"Ohio", "population":7},
 {"state":"Kentucky", "population":26},
 {"state":"Virginia", "population":12},
 {"state":"Indiana", "population":16},
 {"state":"Maine", "population":41},
 {"state":"South Carolina", "population":24},
 {"state":"West Virginia", "population":38},
 {"state":"Maryland", "population":19},
 {"state":"Vermont", "population":50},
 {"state":"New Hampshire", "population":42},
 {"state":"Massachusetts", "population":14},
 {"state":"New Jersey", "population":11},
 {"state":"Hawaii", "population":40},
 {"state":"Connecticut", "population":29},
 {"state":"Delaware", "population":45},
 {"state":"Rhode Island", "population":43},
];
